blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'),
]

project3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 増えた
from django.conf.urls.static import static  # 増えた

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

# 開発環境時のみ、Djangoアプリケーション側でメディアファイルを配信する
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """カテゴリ"""

    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.name


class Post(models.Model):
    """ブログの記事"""

    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    thumbnail = models.ImageField('サムネイル(空欄可)', upload_to='thumbnails/', null=True, blank=True)  # /media/thumbnails/ファイル名
    upload = models.FileField('ファイル', upload_to='uploads/%Y/%m/%d/')  # /media/uploads/2018/3/20/ファイル名
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', auto_now=True)  # 更新するたびにその日時が格納される
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Comment(models.Model):
    """ブログのコメント"""

    name = models.CharField('お名前', max_length=30, default='名無し')
    text = models.TextField('本文')
    post = models.ForeignKey(Post, verbose_name='紐づく記事', on_delete=models.PROTECT)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10]

blog/forms.py
from django import forms
from .models import Comment
from .models import Post


class CommentCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = ('name', 'text')


class VideoCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'thumbnail', 'upload')
        # 少しツウな書き方
        widgets = {
            'title': forms.TextInput(attrs={  # <input type="text" class="form-control"
                'class': 'form-control',
            }),
            'text': forms.Textarea(attrs={  # <textarea class="form-cotrol"
                'class': 'form-control',
            }),
            'thumbnail': forms.ClearableFileInput(attrs={  # <input type="file" class="form-control-file"
                'class': "form-control-file",
            }),
            'upload': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }

blog/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from .forms import CommentCreateForm, VideoCreateForm
from .models import Post, Category, Comment
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset


class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        """
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        """
        category_pk = self.kwargs['pk']
        queryset = Post.objects.order_by('-created_at').filter(category__pk=category_pk)
        return queryset


class DetailView(generic.DetailView):
    model = Post
    form_class = VideoCreateForm
    success_url = reverse_lazy('videos:index')



class CommentView(generic.CreateView):
    model = Comment
    #fields = ('name', 'text')
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['post_pk']
        comment = form.save(commit=False)  # コメントはDBに保存されていません
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()  # ここでDBに保存
        return redirect('blog:detail', pk=post_pk)

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <title>笨笨のブログ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">


  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">ブログ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-3">笨笨のブログ！</h1>
      <p class="lead">フレンチブルドッグに関するブログです</p>
      <hr class="my-2">
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-white">カテゴリ一覧</li>
            {% for category in category_list %}
              <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <footer class="bg-dark text-white text-center py-3">
      <p>あなたの名前</p>  
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-dark">送信</button>
</form>

{% endblock %}

blog/templates/blog/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="card mb-3">
  <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
  <div class="card-body">
    <p>{{ post.created_at }}, {{ post.category }}</p>
    {{ post.text | linebreaksbr | urlize}}
  </div>
  <div class="embed-responsive embed-responsive-16by9">
    <video controls class="embed-responsive-item" src="{{ post.upload.url }}"></video>
  </div>
</div>

{% for comment in post.comment_set.all %}
  <p>
    {{ comment.name }}<br>
    {{ comment.text | linebreaksbr }}
  </p>
{% endfor %}

<a class="btn btn-dark" href="{% url 'blog:comment' post.pk %}">コメント投稿ページへ</a>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% for post in post_list %}
  <div class="card mb-3">
    <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
    <div class="card-body">
      <a href="{% url 'blog:detail' post.pk %}">
        {% if post.thumbnail %}
          <img class="img-thumbnail" src="{{ post.thumbnail.url }}" alt="{{ post.title }}" height="200" width="200">
        {% else %}
          <img class="img-thumbnail" src="{% static 'videos/noimage.jpg' %}"s alt="{{ post.title }}" height="200" width="200">
        {% endif %}
      </a>
      <p>{{ post.created_at }}, {{ post.category }}</p>
      <a href="{% url 'blog:detail' post.pk %}" class="btn btn-dark">続きを読む</a>
    </div>
  </div>
{% endfor %}

{% include 'blog/page.html' %}

{% endblock %}